<?php

/* * *********************************
  Nota di Bob: considerazioni generali:
  - praticamente tutte le stringhe sono da tradurre in italiano
  - all'attivazione del modulo, sarebbe opportuno aggiungere ai profili utenti i campi descrittivi previsti da SPID (codice fiscale, data di nascita, etc...)
  cfr. https://api.drupal.org/api/drupal/modules!field!field.crud.inc/function/field_create_field/7
  - sarebbe utile allegare la libreria SimpleSAMLPHP ( https://simplesamlphp.org/ ) direttamente al modulo, e fornire una configurazione di default coerente
  - documentazione di riferimento:
  http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf
  http://www.agid.gov.it/sites/default/files/regole_tecniche/tabella_attributi_idp_v1_0.pdf

  Più avanti ci sono altri commenti "Nota di Bob" specifici
 */

/**
 * @file
 * simpleSAMLphp authentication module for Drupal.
 *
 * This authentication module is based on the shibboleth authentication module,
 * with changes to adopt to use simpleSAMLphp.
 *
 * ISSUES and TODOs:
 *  ISSUE: User is always dropped on user page after login, instead of where
 *         they were when they clicked "Federated Log In". Because of this, deep
 *         linking to access controlled content does not work. Usability would
 *         be considerably increased if this were resolved.
 *  FYI: Drupal now requires knowledge of the local user password in order to
 *       change e-mail address, etc. This could be an issue for users of
 *       accounts that are autoprovisioned by this module, though Drupal does
 *       give users the ability to reset their password to something they know
 *       via the Request new password feature.
 *  KLUDGE: Drupal does not kill the session on logout, even with
 *          drupal_session_destroy_uid(), so I had to use session_destroy().
 *  @todo Rework the default login limitation logic to use a drupal permission
 *        rather than a list of UIDs.
 *  @todo When denying access because the administrator has chosen not to allow
 *        the module to register/create accounts, the user is told to contact
 *        the administrator; the message should provide the contact information.
 *  ISSUE: Until Drupal issue #754560 is resolved users will not see logout
 *         notices.
 */

/**
 * Implements hook_menu().
 */
function spid_auth_menu() {
    $items = array();

    $items['admin/config/people/spid_auth'] = array(
        'title' => 'Configurazioni SPID Auth',
        'description' => 'Controlla le diverse configurazioni del modulo di autenticazione SPID',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('spid_auth_settings'),
        'access arguments' => array('amministra autenticazione SPID'),
        'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    );
    $items['saml_login'] = array(
        'title' => 'Logon to the site',
        'description' => 'Provides a site login page',
        'page callback' => 'spid_auth_loginpage',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['saml_logout'] = array(
        'title' => 'Logout to the site',
        'description' => 'Provides a site logout page',
        'page callback' => 'spid_auth_logoutpage',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['saml_error'] = array(
        'title' => 'Authentication error page',
        'description' => 'Provides a login error page',
        'page callback' => 'spid_auth_errorpage',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );


    return $items;
}

/**
 * Implements hook_admin_paths().
 */
function spid_auth_admin_paths() {
    return array('admin/config/people/spid_auth' => TRUE);
}

/**
 * Implements hook_help().
 */
function spid_auth_help($path, $arg) {
    switch ($path) {
        case 'admin/config/people/spid_auth':
            $output = t('<p>Questo modulo integra il protocollo di autenticazione SPID in Drupal</p>');
            $output .= t('<p></p>');
            return $output;
    }
}

/**
 * Implements hook_permission().
 */
function spid_auth_permission() {
    return array(
        'amministra autenticazione SPID' => array(
            'title' => t('Amministra autenticazione SPID'),
            'description' => t('Warning: Give to trusted roles only; this permission has security implications.'),
        ),
    );
}

/**
 * Represents the Drupal page (saml_error). 
 */
function spid_auth_errorpage() {
    drupal_set_message(check_plain(t("An authentication error has occurred")));
    drupal_goto('<front>');
}

/**
 * Represents the Drupal page (saml_logout). 
 */
function spid_auth_logoutpage() {

    $state = SimpleSAML_Auth_State::loadState((string) $_REQUEST['LogoutState'], 'MyLogoutState');

    $ls = (isset($state['saml:sp:LogoutStatus']) ? $state['saml:sp:LogoutStatus'] : false); /* Only works for SAML SP */
    if ($ls && $ls['Code'] === 'urn:oasis:names:tc:SAML:2.0:status:Success' && !isset($ls['SubCode'])) {
        /* Successful logout. */
        $msg = t("You have been logged out.");
    } else {
        /* Logout failed. Tell the user to close the browser. */
        $msg = t("We were unable to log you out of all your sessions. To be completely sure that you are logged out, you need to close your web browser.");
    }
    drupal_set_message(check_plain($msg));
    drupal_goto('<front>');
}

/**
 * Represents the Drupal page (saml_login), which triggers user authentication against the SimpleSAMLphp service provider.
 */
function spid_auth_loginpage() {

    global $user;
    global $base_url;
    global $_simplesamlphp_auth_as;

    $fail = NULL;
    $output = NULL;

    if (!_spid_auth_isEnabled()) {
        // Exit without initializing.
        drupal_set_message(t('We\'re sorry this feature is not yet enabled.'));

        return '';
    }
    // Do some sanity checking before attempting anything.
    $config = SimpleSAML_Configuration::getInstance();
    $configStoreType = $config->getValue('store.type');

    // Make sure phpsession is NOT being used.
    if ($configStoreType == 'phpsession') {
        watchdog('spid_auth', 'A user attempted to login using simplesamlphp but the store.type is phpsession, use memcache or sql for simplesamlphp session storage. See: simplesamlphp/config/config.php.', NULL, WATCHDOG_WARNING);
        $fail = TRUE;
    }

    // Make sure there is an instance of SimpleSAML_Auth_Simple.
    if (!$_simplesamlphp_auth_as) {
        watchdog('spid_auth', 'A user attempted to login using this module but there was a problem.', NULL, WATCHDOG_WARNING);
        $fail = TRUE;
    }

    // There was a problem, we can't go on, but we don't want to tell the user any specifics either.
    if ($fail) {
        drupal_set_message(t('We\'re sorry. There was a problem. The issue has been logged for the administrator.'));
        drupal_goto('<front>');
    }
    $returnto = NULL;

    // Support for deep linking.
    // See if a URL has been explicitly provided in ReturnTo. If so, use it (as long as it points to this site).
    if ((isset($_REQUEST['ReturnTo']) && $_REQUEST['ReturnTo']) &&
            (valid_url($_REQUEST['ReturnTo']) && stristr($_REQUEST['ReturnTo'], $base_url))) {

        $returnto = $_REQUEST['ReturnTo'];

        // If not, see if a REFERER URL is available. If so, use it (as long as it points to this site).
    } elseif ((isset($_SERVER['HTTP_REFERER']) && $_SERVER['HTTP_REFERER']) &&
            (valid_url($_SERVER['HTTP_REFERER']) && stristr($_SERVER['HTTP_REFERER'], $base_url))) {

        $returnto = $_SERVER['HTTP_REFERER'];
    }


    // If the user is anonymous, set the cookie (if we can) and require authentication.
    if ($user->uid == 0) {

        if ($returnto) {
            // Set the cookie so we can deliver the user to the place they started
            setrawcookie('spid_auth_returnto', $returnto, time() + 60 * 60);
            //setrawcookie('SimpleSAMLSessionID', $returnto, time() + 60 * 60);
        }


        // Check 
        if ((isset($_REQUEST['infocert_id']) && $_REQUEST['infocert_id'])) {
            $options['saml:idp'] = $_REQUEST['infocert_id'];
        } elseif ((isset($_REQUEST['poste_id']) && $_REQUEST['poste_id'])) {
            $options['saml:idp'] = $_REQUEST['poste_id'];
        } elseif ((isset($_REQUEST['tim_id']) && $_REQUEST['tim_id'])) {
            $options['saml:idp'] = $_REQUEST['tim_id'];
        } else {
            drupal_set_message(t('We\'re sorry. There was a problem. The issue has been logged for the administrator.'));
            drupal_goto('<front>');
        }

        // Require the user to be authenticated.
        // Last char rapresent Level authentication 
        $options['saml:AuthnContextClassRef'] = 'urn:oasis:names:tc:SAML:2.0:ac:classes:SpidL' . variable_get('spid_auth_authlevel', 1);
        $options['samlp:RequestedAuthnContext'] = array("Comparison" => "minimum");
        /* indicando la url di ritorno, funziona anche dietro reverse proxy */
        /* se invece si lascia quella di default no */

        $options['ReturnTo'] = url('saml_login', array('absolute' => true));
        $options['ErrorURL'] = url('saml_error', array('absolute' => true));

        $_simplesamlphp_auth_as->requireAuth($options);

        // If the user is authenticated, send them along.
    } else {

        $gotourl = NULL;

        // Check to see if we've set a cookie. If there is one, give it priority.
        if (isset($_COOKIE['spid_auth_returnto']) && $_COOKIE['spid_auth_returnto']) {
            // use the cookie for the ReturnTo
            $gotourl = $_COOKIE['spid_auth_returnto'];

            // unset the cookie
            setrawcookie('spid_auth_returnto', '');
        } elseif ($returnto) {
            $gotourl = $returnto;
        }


        // If a ReturnTo has been set.
        if ($gotourl) {
            drupal_goto(str_replace($base_url . '/', '', $gotourl));
        } else {
            drupal_goto('user/' . $user->uid);
        }
    }
    return $output;
}

/**
 * Implements hook_init().
 */
function spid_auth_init() {
    global $user;
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;
    global $_simplesamlphp_auth_saml_config;
    global $_simplesamlphp_auth_saml_version;

    if (!_spid_auth_isEnabled(TRUE)) {
        // Exit without initializing.
        return;
    }

    // Get the simplesamlphp session.
    $basedir = variable_get('spid_auth_installdir', '/var/simplesamlphp');

    require_once($basedir . '/lib/_autoload.php');

    $_simplesamlphp_auth_saml_config = SimpleSAML_Configuration::getInstance();
    $_simplesamlphp_auth_saml_version = $_simplesamlphp_auth_saml_config->getVersion();

    // Load simpleSAMLphp, configuration and metadata.
    $_simplesamlphp_auth_as = new SimpleSAML_Auth_Simple(variable_get('spid_auth_authsource', 'default-sp'));
    $_simplesamlphp_auth_saml_attributes = $_simplesamlphp_auth_as->getAttributes();

    if ($user->uid == 0) {
        // User is not logged in to Drupal.
        if ($_simplesamlphp_auth_as->isAuthenticated()) {
            // User is logged in - SimpleSAMLphp (but not Drupal).
            // Get unique identifier from saml attributes.

            $authname = _spid_auth_get_authname();

            _simplesaml_auth_debug(t('Authname is [%authname] userid is [%uid]', array('%authname' => $authname, '%uid' => $user->uid)));

            if (!empty($authname)) {
                // User is logged in with SAML authentication and we got the unique identifier.
                // Try to log into Drupal.
                _simplesaml_auth_debug(t('Load user [%authname]', array('%authname' => $authname)));

                // Retrieve user mapping and attempt to log the user in.
                $ext_user = user_external_load($authname);

                if (!$ext_user) {
                    // First we check the admin settings for simpleSAMLphp and find out if we are allowed to register users.
                    if (variable_get('spid_auth_registerusers', TRUE)) {

                        // We are allowed to register new users.
                        _simplesaml_auth_debug(t('Register [%authname]', array('%authname' => $authname)));

                        user_external_login_register($authname, 'spid_auth');

                        if ($user) {
                            // Populate roles based on configuration setting.
                            $roles = _spid_auth_rolepopulation(variable_get('spid_auth_rolepopulation', ''));
                            $userinfo = array('roles' => $roles);
                            $user = user_save($user, $userinfo); // @todo - Fjernet rolle-delen her da den gav en bra feilmelding når roller ikke finnes ;)
                        }
                    } else {
                        // We are not allowed to register new users on the site through simpleSAML.
                        // We let the user know about this and redirect to the user/login page.
                        $msg = t("We are sorry. While you have successfully authenticated, you are not yet entitled to access this site. Please ask the site administrator to provision access for you.");
                        drupal_set_message(check_plain($msg));
                        $_simplesamlphp_auth_as->logout(base_path());
                    }
                } else {
                    // If successfully logged into Drupal.
                    // See if we're supposed to re-evaluate role assignments.

                    if (variable_get('spid_auth_roleevaleverytime', 0)) {
                        // If the user is already registered...
                        // Update the roles.
                        // Populate roles based on configuration setting.
                        _simplesaml_auth_debug(t('User already registered [%authname] updating roles.', array('%authname' => $authname)));
                        $roles = _spid_auth_rolepopulation(variable_get('spid_auth_rolepopulation', ''));
                        $userinfo = array('roles' => $roles);

                        // Save the updated roles and populate the user object.
                        $user = user_save($ext_user, $userinfo);
                    } else {
                        // No need to evaluate roles, populate the user object.
                        $user = $ext_user;
                    }

                    if (module_exists('rules')) {
                        rules_invoke_event('spid_auth_rules_event_login', $user);
                    }
                }

                // Finalizing the login, calls hook_user op login.
                $edit = array();
                user_login_finalize($edit);
            } // End if !empty authname.
        } // End if isset saml_session.
    } else {
        // The user is already logged into Drupal.
        // If we forbid users from logging in using local accounts.
        if (FALSE == variable_get('spid_auth_allowdefaultlogin', TRUE)) {
            // If the user has NOT been authenticated via simpleSAML...
            if (!$_simplesamlphp_auth_as->isAuthenticated()) {
                // :FYI: Until Drupal issue #754560 is corrected this message will never be seen by the user.
                drupal_set_message(t("We are sorry, users are not permitted to log in using local accounts."));
                // Destroy the user's session (log them out).
                _spid_auth_destroy_drupal_session();
            }
        } else {
            // If we are allowing users to log in with local accounts.
            // If the user has NOT been authenticated via simpleSAML.
            if (!$_simplesamlphp_auth_as->isAuthenticated()) {

                // See if we limit this privilege to specified users
                $strAllwDefLogUsers = variable_get('spid_auth_allowdefaultloginusers', '');
                $arrAllwDefLogUsers = array();
                // See if we limit this privilege to specified roles.
                $arrAllwDefLogRoles = variable_get('spid_auth_allowdefaultloginroles', FALSE);

                // If user IDs or roles are specified, we let them in, but everyone else gets logged out.
                if (drupal_strlen($strAllwDefLogUsers) || $arrAllwDefLogRoles) {

                    // Convert the string into an array.
                    // @todo Perform a test to make sure that only numbers, spaces, or commas are in the string.
                    $arrAllwDefLogUsers = explode(',', $strAllwDefLogUsers);

                    // If we still have something to work with.
                    if (0 < count($arrAllwDefLogUsers) || 0 < count($arrAllwDefLogRoles)) {
                        /* Log the user out of Drupal if:
                          1) the current user's uid is NOT in the list of allowed uids...
                          2) or their role does not match and allowed mixed mode role. */
                        $matchRoles = array_intersect(array_keys($user->roles), $arrAllwDefLogRoles);
                        if (!in_array($user->uid, $arrAllwDefLogUsers) && count($matchRoles) == 0) {
                            // User is logged into Drupal, but may not be logged into simpleSAML.
                            // If this is the case we're supposed to log the user out of Drupal.
                            // :FYI: Until Drupal issue #754560 is corrected this message will never be seen by the user.
                            drupal_set_message(t("We are sorry, you are not permitted to log in using a local account."));

                            // The least we can do is write something to the watchdog so someone will know what's happening.
                            watchdog('spid_auth', 'User %name not authorized to log in using local account.', array('%name' => $user->name));

                            _spid_auth_destroy_drupal_session();
                        }
                    }
                } // Test for specified users.
            } // End if $_simplesamlphp_auth_as->isAuthenticated().
        } // End test to see if we allow default logins.
    } // End if user->uid.
}

/**
 * Implements hook_user_insert().
 */
function spid_auth_user_insert(&$edit, $account, $category = NULL) {
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;

    if (!_spid_auth_isEnabled()) {
        // Exit without initializing.
        return;
    }

    if ($category == 'account') {
        // If user registration has a valid session...
        if ($_simplesamlphp_auth_as->isAuthenticated()) {
            // Get name from default attributes.
            try {
                _simplesaml_auth_debug(t('Registering user [%acctname]', array('%acctname' => $account->name)));
                $account->name = _spid_auth_get_fiscal_number($account->uid);
            } catch (Exception $e) {
                drupal_set_message(t('Your user name was not provided by your identity provider (IDP).'), "error");
                watchdog('spid_auth', $e->getMessage(), NULL, WATCHDOG_CRITICAL);
            }

            db_update('users')
                    ->fields(array('name' => $account->name))
                    ->condition('uid', $account->uid)
                    ->execute();

            _simplesaml_auth_debug(t('Updating username [%acctname]', array('%acctname' => $account->name)));

            // Get mail from default attribute.
            try {
                $mail_address = _spid_auth_get_mail();
            } catch (Exception $e) {
                drupal_set_message(t('Your e-mail address was not provided by your identity provider (IDP).'), "error");
                watchdog('spid_auth', $e->getMessage(), NULL, WATCHDOG_CRITICAL);
            }

            if (!empty($mail_address)) {
                db_update('users')
                        ->fields(array('mail' => $mail_address))
                        ->condition('uid', $account->uid)
                        ->execute();
            }

            if (module_exists('rules')) {
                rules_invoke_event('spid_auth_rules_event_register', $account);
            }

            _simplesaml_auth_debug(t('Updating mail [%mailaddr]', array('%mailaddr' => $mail_address)));
        }
    }
}

/**
 * Implements hook_user_logout().
 */
function spid_auth_user_logout($account) {
    global $user;
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;
    global $base_url;

    if (!empty($_simplesamlphp_auth_saml_attributes)) {

        $config = SimpleSAML_Configuration::getInstance();

        // :KLUDGE: for some reason Drupal is not killing the session, even if I were to call drupal_session_destroy_uid() here.
        session_destroy();

        $gotourl = base_path();

        if (variable_get('spid_auth_logoutgotourl', '')) {
            $gotourl = variable_get('spid_auth_logoutgotourl', '');
        }

        $_simplesamlphp_auth_as->logout(array(
            'ReturnTo' => url('saml_logout'),
            'ReturnStateParam' => 'LogoutState',
            'ReturnStateStage' => 'MyLogoutState'));
    }
}

/**
 * Implements hook_user_delete().
 */
function spid_auth_user_delete($account) {
    db_delete('authmap')
            ->condition('uid', $account->uid)
            ->condition('authname', $account->name)
            ->execute();
}

/**
 * Implements settings for the module.
 */
function spid_auth_settings() {
    global $_simplesamlphp_auth_saml_version, $base_url;

    if (!empty($_simplesamlphp_auth_saml_version)) {
        $ver = explode('.', $_simplesamlphp_auth_saml_version);
        if (!($ver[0] >= 1 && $ver[1] >= 5)) {
            drupal_set_message(t("Please upgrade SimpleSAMLphp. You are using %ssp_version", array('%ssp_version' => $_simplesamlphp_auth_saml_version)), 'warning');
        }
    }

    $roles = user_roles(TRUE);

    $form['spid_auth_grp_setup'] = array(
        '#type' => 'fieldset',
        '#title' => t('Basic Setup'),
        '#collapsible' => FALSE,
    );
    $form['spid_auth_grp_setup']['spid_auth_activate'] = array(
        '#type' => 'checkbox',
        '#title' => t('Attiva autenticazione SPID'),
        '#default_value' => variable_get('spid_auth_activate', FALSE),
        '#description' => t('Checking this box before configuring the module could lock you out of Drupal.'),
    );
    /*     * *********************************
      Nota di Bob: allegando la libreria in oggetto al modulo stesso, si può evitare di chiedere questi dettagli tecnici
     */
    $form['spid_auth_grp_setup']['spid_auth_installdir'] = array(
        '#type' => 'textfield',
        '#title' => t('Installation directory (default: /var/simplesamlphp)'),
        '#default_value' => variable_get('spid_auth_installdir', '/var/simplesamlphp'),
        '#description' => t('The base directory of simpleSAMLphp. Absolute path with no trailing slash.'),
    );
    $form['spid_auth_grp_setup']['spid_auth_authsource'] = array(
        '#type' => 'textfield',
        '#title' => t('Authenticaton source for this SP (default: default-sp)'),
        '#default_value' => variable_get('spid_auth_authsource', 'default-sp'),
        '#description' => t('The name of the source to use from /var/simplesamlphp/config/authsources.php'),
    );
    $form['spid_auth_grp_setup']['spid_auth_authlevel'] = array(
        '#type' => 'radios',
        '#title' => t('Authenticaton level for this SP (default: default-sp)'),
        '#default_value' => variable_get('spid_auth_authlevel', 1),
        '#description' => t('Authentication level used'),
        '#options' => array(
            1 => 1,
            2 => 2,
            3 => 3)
    );


    $form['spid_auth_grp_setup']['spid_auth_authsource_infocert'] = array(
        '#type' => 'textfield',
        '#title' => t('Autenticaton id for Infocert'),
        '#default_value' => variable_get('spid_auth_authsource_infocert'),
        '#description' => t('The name of the infocert_id from /var/simplesamlphp/config/authsources.php'),
    );
    $form['spid_auth_grp_setup']['spid_auth_authsource_poste'] = array(
        '#type' => 'textfield',
        '#title' => t('Autenticaton id for Poste'),
        '#default_value' => variable_get('spid_auth_authsource_poste'),
        '#description' => t('The name of the poste_id from /var/simplesamlphp/config/authsources.php'),
    );
    $form['spid_auth_grp_setup']['spid_auth_authsource_tim'] = array(
        '#type' => 'textfield',
        '#title' => t('Autenticaton id for Tim'),
        '#default_value' => variable_get('spid_auth_authsource_tim'),
        '#description' => t('The name of the tim_id from /var/simplesamlphp/config/authsources.php'),
    );

    $form['spid_auth_grp_setup']['spid_auth_forcehttps'] = array(
        '#type' => 'checkbox',
        '#title' => t('Force https for login links'),
        '#default_value' => variable_get('spid_auth_forcehttps', TRUE),
        '#description' => t('Should be enabled on production sites.'),
    );

    $form['spid_auth_grp_user'] = array(
        '#type' => 'fieldset',
        '#title' => t('User Info and Syncing'),
        '#collapsible' => FALSE,
    );
    $form['spid_auth_grp_user']['spid_auth_rolepopulation'] = array(
        '#type' => 'textarea',
        '#title' => t('Automatic role population from simpleSAMLphp attributes'),
        '#default_value' => variable_get('spid_auth_rolepopulation', ''),
        '#description' => t('A pipe separated list of rules.<br />Example: <i>roleid1:condition1|roleid2:contition2...</i> <br />For instance: <i>4:all;1:eduPersonPrincipalName,@=,uninett.no;affiliation,=,employee|2:mail,=,andreas@uninett.no</i>'),
    );
    $form['spid_auth_grp_user']['spid_auth_roleevaleverytime'] = array(
        '#type' => 'checkbox',
        '#title' => t('Reevaluate roles every time the user logs in.'),
        '#default_value' => variable_get('spid_auth_roleevaleverytime', 0),
        '#description' => t('NOTE: This means users could loose any roles that have been assigned manually in Drupal.'),
    );

    $form['spid_auth_grp_reg'] = array(
        '#type' => 'fieldset',
        '#title' => t('User Provisioning'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
    );
    $form['spid_auth_grp_reg']['spid_auth_registerusers'] = array(
        '#type' => 'checkbox',
        '#title' => t('Register users (i.e., auto-provisioning)'),
        '#default_value' => variable_get('spid_auth_registerusers', TRUE),
        '#description' => t('Determines wether or not the module should automatically create/register new Drupal accounts for users that authenticate using SimpleSAMLphp. Unless you\'ve done some custom work to provision Drupal accounts with the necessary authmap entries you will want this checked.<br /><br />NOTE: If unchecked each user must already have been provisioned a Drupal account with an appropriate entry in the authmap table before logging in. Otherwise they will receive a notice and be denied access. Be aware that simply creating a Drupal account will not create the necessary entry in the authmap table.'),
    );

    $form['spid_auth_grp_auth'] = array(
        '#type' => 'fieldset',
        '#title' => t('Drupal Authentication'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
    );

    /*     * *********************************
      Nota di Bob: questa possibilità penso che debba essere tolta del tutto
     */
    $form['spid_auth_grp_auth']['spid_auth_allowdefaultlogin'] = array(
        '#type' => 'checkbox',
        '#title' => t('Allow authentication with local Drupal accounts'),
        '#default_value' => variable_get('spid_auth_allowdefaultlogin', TRUE),
        '#description' => t('Check this box if you want to let people log in with local Drupal accounts (without using simpleSAMLphp). If you want to restrict this privilege to certain users you can enter the Drupal user IDs in the field below.'),
    );
    $form['spid_auth_grp_auth']['spid_auth_allowdefaultloginroles'] = array(
        '#type' => 'select',
        '#size' => 3,
        '#options' => $roles,
        '#multiple' => TRUE,
        '#title' => t('Which ROLES should be allowed to login with local accounts?'),
        '#default_value' => variable_get('spid_auth_allowdefaultloginroles', ''),
        '#description' => t('Roles that should be allowed to login without simpleSAMLphp. Examples are dev/admin roles or guest roles.'),
    );
    $form['spid_auth_grp_auth']['spid_auth_allowdefaultloginusers'] = array(
        '#type' => 'textfield',
        '#title' => t('Which users should be allowed to login with local accounts?'),
        '#default_value' => variable_get('spid_auth_allowdefaultloginusers', ''),
        '#description' => t('Example: <i>1,2,3</i><br />A comma-separated list of user IDs that should be allowed to login without simpleSAMLphp. If left blank, all local accounts can login.'),
    );
    $form['spid_auth_grp_auth']['spid_auth_logoutgotourl'] = array(
        '#type' => 'textfield',
        '#title' => t('Optionally, specify a URL for users to go to after logging out'),
        '#default_value' => variable_get('spid_auth_logoutgotourl', ''),
        '#description' => t('Example: ' . $base_url),
    );

    return system_settings_form($form);
}

/**
 * Implements hook_block_view().
 */
function spid_auth_block_view($delta = '') {

    if (!_spid_auth_isEnabled()) {
        // Exit without executing.
        return;
    }

    switch ($delta) {
        case 0:
            $block = array('subject' => '',
                'content' => _spid_auth_generate_block_text());
            break;
    }
    return $block;
}

/**
 * Implements hook_block_info().
 */
function spid_auth_block_info() {
    $block = array(
        array(
            'info' => t('simpleSAMLphp authentication'),
            'cache' => DRUPAL_NO_CACHE,
        )
    );
    return $block;
}

/* * **************************************************************************
 * Private functions ********************************************************
 * ************************************************************************** */

/**
 * Checks to see if authentication via SimpleSAMLphp should be activated
 *
 * @param bShowInactiveMsg
 *   Whether to display the "module not activated" message
 *
 * @return
 *   TRUE/FALSE
 */
function _spid_auth_isEnabled($bShowInactiveMsg = FALSE) {
    GLOBAL $user;

    $failure = NULL;
    $isActivated = variable_get('spid_auth_activate');
    $basedir = variable_get('spid_auth_installdir', '/var/simplesamlphp');

    if (!$isActivated) {
        $adminPath = array_keys(spid_auth_admin_paths());
        $failure = t('L\'autenticazione SPID non è ancora stata attivita. Può essere attivata dalla ' . l('pagina di configurazione', $adminPath[0]) . '.');

        watchdog('spid_auth', $failure, NULL, WATCHDOG_WARNING);
    } else {

        // Make sure we know where SimpleSAMLphp is.
        if (!file_exists($basedir)) {
            $failure = t('SimpleSAMLphp could not be found at %basedir . The spid_auth module cannot function until the path to the local SimpleSAMLphp instance is configured.', array('%basedir' => $basedir));

            watchdog('spid_auth', $failure, NULL, WATCHDOG_WARNING);
        }
    }

    // If there were no failures, then it should be activated
    if (!$failure) {
        return TRUE;
    } else {

        // communicate but don't be too annoying
        if ($bShowInactiveMsg && (1 == $user->uid || user_access('access administration pages')) && ( preg_match('/admin\/people/', request_uri()) || preg_match('/admin\/modules/', request_uri()) || preg_match('/admin\/config/', request_uri()) )) {
            drupal_set_message($failure);
        }
    }

    return FALSE;
}

/**
 * Gets the authname attribute from the SAML assertion.
 * Auth_name can't be spidCode because a singol user can have tree SPID authentication 
 * with tree different idp (so he has a single user but tree spidCode) 
 *  
 * @return
 *   The authname attribute.
 */
function _spid_auth_get_authname() {
    global $_simplesamlphp_auth_saml_attributes;

    $authname = '';

    // Check if valid local session exists..
    if (isset($_simplesamlphp_auth_saml_attributes)) {
        _simplesaml_auth_debug(t('_spid_auth_get_authname: Valid local session exist'));
        if (isset($_simplesamlphp_auth_saml_attributes['fiscalNumber'])) {
            $authname = $_simplesamlphp_auth_saml_attributes['fiscalNumber'][0];
        } else if (isset($_simplesamlphp_auth_saml_attributes['ivaCode'])) {
            $authname = $_simplesamlphp_auth_saml_attributes['ivaCode'][0];
        } else {
            throw new Exception(t('error in spid_auth.module: no valid unique id attribute set'));
        }
    }

    $authname = substr($authname, 6);

    return $authname;
}

/**
 * Gets the default fiscal number from the SAML assertion.
 *
 * @return
 *   The name attribute.
 */
function _spid_auth_get_fiscal_number($account) {
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;

    $fiscal_number = '';

    // Check if valid local session exists..
    if ($_simplesamlphp_auth_as->isAuthenticated()) {
        if ((isset($_simplesamlphp_auth_saml_attributes['fiscalNumber'])) &&
                (isset($_simplesamlphp_auth_saml_attributes['fiscalNumber'][0])) &&
                ($_simplesamlphp_auth_saml_attributes['fiscalNumber'][0] !== '')) {
            $fiscal_number = substr($_simplesamlphp_auth_saml_attributes['fiscalNumber'][0], 6);
        } elseif ((isset($_simplesamlphp_auth_saml_attributes['ivaCode'])) &&
                (isset($_simplesamlphp_auth_saml_attributes['ivaCode'][0])) &&
                ($_simplesamlphp_auth_saml_attributes['ivaCode'][0] !== '')) {

            $iva_code = substr($_simplesamlphp_auth_saml_attributes['ivaCode'][0], 6);
        } else {
            throw new Exception(t('Non sono stati settati gli attributi ivaCode oppure fiscalNumber per l\'utente %uid.', array(
                '%uid' => $account,
            )));
        }
    }
    return $fiscal_number ? $fiscal_number : $iva_code;
}

/**
 * Gets the default name attribute from the SAML assertion.
 *
 * @return
 *   The name attribute.
 */
function _spid_auth_get_default_name($account) {
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;

    $default_name = '';

    // Check if valid local session exists..
    if ($_simplesamlphp_auth_as->isAuthenticated()) {
        if ((!isset($_simplesamlphp_auth_saml_attributes['name'])) ||
                (!isset($_simplesamlphp_auth_saml_attributes['familyName'])) ||
                (!isset($_simplesamlphp_auth_saml_attributes['name'][0])) ||
                (!isset($_simplesamlphp_auth_saml_attributes['familyName'][0])) ||
                ($_simplesamlphp_auth_saml_attributes['name'][0] == '') ||
                ($_simplesamlphp_auth_saml_attributes['familyName'][0] == '')) {
            throw new Exception(t('Non sono stati settati gli attributi "name" e "familyName" per l\'utente %uid.', array(
                '%uid' => $account,
            )));
        }

        $default_name = $_simplesamlphp_auth_saml_attributes['name'][0] . ' ' . $_simplesamlphp_auth_saml_attributes['familyName'][0];
    }
    return $default_name;
}

/**
 * Gets the mail attribute.
 *
 * @return
 *   The mail attribute.
 */
function _spid_auth_get_mail() {
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;
    $mail_address = '';
    // Check if valid local session exists..
    if ($_simplesamlphp_auth_as->isAuthenticated()) {
        if (isset($_simplesamlphp_auth_saml_attributes['email'])) {
            $mail_address = $_simplesamlphp_auth_saml_attributes['email'][0];
        } else {
            throw new Exception(t('Error in spid_auth.module: No valid mail attribute set.'));
        }
    }

    return $mail_address;
}

/**
 * Forces HTTPS connections.
 */
function _spid_auth_forcehttps_rewrite($url) {
    if (variable_get('spid_auth_forcehttps', TRUE)) {
        $url = str_replace('http://', 'https://', $url);
        _simplesaml_auth_debug('forcehttps rewrite: ' . $url);
    }

    return $url;
}

/**
 * Generates the text for the log in block.
 */
function _spid_auth_generate_block_text() {
    global $_simplesamlphp_auth_as;
    $block_content = '';
    global $user;

    if (!_spid_auth_isEnabled()) {
        // Exit without executing.
        return;
    }

    // Check if valid local session exists..
    if ($_simplesamlphp_auth_as->isAuthenticated() or $user->uid != 0) {
        $block_content .= '<p>' . t('Logged in as: ') . $user->name . '<br />' . l('Log Out', 'user/logout') . '</a></p>';
    } else {
        //$block_content .= '<p>' . l('Federated Log In', 'saml_login') . '</p>';
        $block_content .= '<p>' . _spid_auth_spidbutton() . '</p>';
    }

    return $block_content;
}

/**
 * Evaluates a role rule.
 *
 * @param $roleruleevaluation
 *   An array containing the role rule to evaluate.
 * @param $attributes
 *   An array containing the identity attributes.
 *
 * @return
 *   An array containing role value and the attribute, or FALSE.
 */
function _spid_auth_evaulaterolerule($roleruleevaluation, $attributes) {
    _simplesaml_auth_debug(t('Evaluate rule (key=%key,operator=%op,value=%val)', array(
        '%key' => isset($roleruleevaluation[0]) ? $roleruleevaluation[0] : "not set",
        '%op' => isset($roleruleevaluation[1]) ? $roleruleevaluation[1] : "not set",
        '%val' => isset($roleruleevaluation[2]) ? $roleruleevaluation[2] : "not set"
    )));

    if ($roleruleevaluation[0] == 'all') {
        return TRUE;
    }

    if (!array_key_exists($roleruleevaluation[0], $attributes)) {
        return FALSE;
    }

    $attribute = $attributes[$roleruleevaluation[0]];

    switch ($roleruleevaluation[1]) {
        case '=' :
            return in_array($roleruleevaluation[2], $attribute);

        case '@=' :
            $dc = explode('@', $attribute[0]);
            if (count($dc) != 2) {
                return FALSE;
            }
            return ($dc[1] == $roleruleevaluation[2]);
    }

    return FALSE;
}

/**
 * Performs role population.
 *
 * @param $rolemap
 *   A string containing the role map.
 *
 * @return
 *   An array containing user's roles.
 */
function _spid_auth_rolepopulation($rolemap) {
    global $_simplesamlphp_auth_as;
    global $_simplesamlphp_auth_saml_attributes;
    $roles = array();

    _simplesaml_auth_debug(t('Rolemap: %rolemap', array('%rolemap' => $rolemap)));

    // Check if valid local session exists..
    if ($_simplesamlphp_auth_as->isAuthenticated()) {
        $attributes = $_simplesamlphp_auth_saml_attributes;

        if (empty($rolemap)) {
            return $roles;
        }

        _simplesaml_auth_debug(t('Evaluate rolemap: %rolemap', array('%rolemap' => $rolemap)));

        $rolerules = explode('|', $rolemap);

        foreach ($rolerules AS $rolerule) {
            _simplesaml_auth_debug(t('Evaluate role rule: %rolerule', array('%rolerule' => $rolerule)));

            $roleruledecompose = explode(':', $rolerule);

            $roleid = $roleruledecompose[0];
            $roleruleevaluations = explode(';', $roleruledecompose[1]);
            $addnew = TRUE;
            foreach ($roleruleevaluations AS $roleruleevaluation) {
                _simplesaml_auth_debug(t('Evaluate role evaulation: %roleruleeval', array('%roleruleeval' => $roleruleevaluation)));

                $roleruleevaluationdc = explode(',', $roleruleevaluation);

                if (!_spid_auth_evaulaterolerule($roleruleevaluationdc, $attributes)) {
                    $addnew = FALSE;
                }
            }
            if ($addnew) {
                $roles[$roleid] = $roleid;
                _simplesaml_auth_debug(t('Add new role: %roleid', array('%roleid' => $roleid)));
            }
        }
    }

    return $roles;
}

/**
 * See if the user has an authmap record for spid_auth
 */
function _simplesaml_auth_user_has_authmap($authname) {
    $authmaps = user_get_authmaps($authname);

    $return = 0;

    if (is_array($authmaps)) {
        $return = in_array('spid_auth', array_keys($authmaps));
    }

    return $return;
}

/**
 * This helper function is used by developers to debug the form API workflow in this module.
 */
function _simplesaml_auth_debug($message) {
    watchdog('spid_auth', $message, NULL, WATCHDOG_DEBUG);
}

/**
 * Helper function for logging out a user that is has a active session in Drupal but not with simpleSAML.
 */
function _spid_auth_destroy_drupal_session() {
    global $user;

    watchdog('user', 'Session closed for %name.', array('%name' => $user->name));

    // Destroy the current session:
    session_destroy();
    // Only variables can be passed by reference workaround.
    $NULL = NULL;
    user_module_invoke('logout', $NULL, $user);

    // Load the anonymous user.
    $user = drupal_anonymous_user();

    drupal_goto();
}

/* * **************************************************************************
 * Public functions *********************************************************
 * ************************************************************************** */

/**
 * Determine if the current user is authenticated through SAML.
 *
 * @return
 *   TRUE if the current user is authenticated through SAML.  FALSE otherwise.
 */
function spid_auth_is_authenticated() {
    global $_simplesamlphp_auth_as;

    // Assume that the user isn't authenticated until proven otherwise.
    $authenticated = FALSE;

    // If the associated global variable exists, and the auth flag is set, note it.
    if (isset($_simplesamlphp_auth_as) && $_simplesamlphp_auth_as->isAuthenticated()) {
        $authenticated = TRUE;
    }

    // Return the result.
    return $authenticated;
}

/**
 * Return any attributes provided by the SAML IDP.
 *
 * @param $attribute
 *   The attribute whose value to return.  Can be skipped if all attribute
 *   values are requested.
 *
 * @return
 *   If an attribute was provided, the value of the attribute is returned.
 *   Otherwise, an array of all attribute values is returned, keyed by
 *   attribute.
 */
function spid_auth_get_attributes($attribute = NULL) {
    global $_simplesamlphp_auth_saml_attributes;

    if (isset($attribute)) {

        // Initially, assume that there's nothing to return.
        $result = NULL;

        // If the specified attribute is set, grab it.
        if (isset($_simplesamlphp_auth_saml_attributes)) {
            if (isset($_simplesamlphp_auth_saml_attributes[$attribute])) {
                $result = $_simplesamlphp_auth_saml_attributes[$attribute];
            }
        }
    }

    // No specific attribute was requested; return all of them.
    else {

        // Initially, assume that there's nothing to return.
        $result = array();

        // If the global array exists, return it.
        if (isset($_simplesamlphp_auth_saml_attributes)) {
            $result = $_simplesamlphp_auth_saml_attributes;
        }
    }

    // Return whatever we've got.`
    return $result;
}

/**
 * 
 * Generate the button source code according to AGID specs,
 * using AGID vendor folder.
 * 
 * 
 * @return 
 *   A string containing the source code that generate the Login Button 
 */
function _spid_auth_spidbutton() {

    // la base_url è necessaria in caso di reverse proxy 

    $spid_ico_circle_svg = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-ico-circle-bb.svg';
    $spid_ico_circle_png = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-ico-circle-bb.png';

    $spid_idp_infocert_svg = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-infocertid.svg';
    $spid_idp_infocert_png = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-infocertid.png';

    $spid_idp_timid_svg = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-timid.svg';
    $spid_idp_timid_png = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-timid.png';

    $spid_idp_posteid_svg = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-posteid.svg';
    $spid_idp_posteid_png = drupal_get_path('module', "spid_auth") . '/vendor/agid/img/spid-idp-posteid.png';

    $infocert_id = variable_get('spid_auth_authsource_infocert');
    $poste_id = variable_get('spid_auth_authsource_poste');
    $tim_id = variable_get('spid_auth_authsource_tim');



    $formaction = url('saml_login', array('absolute' => true));

    $spid_bottone = <<<BOTTONE
    <form name="spid_idp_access" action="$formaction" method="post">
        <a href="#" class="italia-it-button italia-it-button-size-s button-spid" spid-idp-button="#spid-idp-button-small-post" aria-haspopup="true" aria-expanded="false">
            <span class="italia-it-button-icon"><img src="$spid_ico_circle_svg" onerror="this.src='$spid_ico_circle_png'; this.onerror=null;" alt="" /></span>
            <span class="italia-it-button-text">Entra con SPID</span>
        </a>
        <div id="spid-idp-button-small-post" class="spid-idp-button spid-idp-button-tip spid-idp-button-relative">
            <ul id="spid-idp-list-small-root-post" class="spid-idp-button-menu" aria-labelledby="spid-idp">
                <li class="spid-idp-button-link">
                    <button class="idp-button-idp-logo" name="infocert_id" type="submit" value="$infocert_id"><span class="spid-sr-only">Infocert ID</span><img class="spid-idp-button-logo" src="$spid_idp_infocert_svg" onerror="this.src='$spid_idp_infocert_png'; this.onerror=null;" alt="Infocert ID" /></button>
                </li>
                <li class="spid-idp-button-link">
                    <button class="idp-button-idp-logo" name="poste_id" type="submit" value="$poste_id"><span class="spid-sr-only">Poste ID</span><img class="spid-idp-button-logo" src="$spid_idp_posteid_svg" onerror="this.src='$spid_idp_posteid_png'; this.onerror=null;" alt="Poste ID" /></button>
                </li>
                <li class="spid-idp-button-link">
                    <button class="idp-button-idp-logo" name="tim_id" type="submit" value="$tim_id"><span class="spid-sr-only">Tim ID</span><img class="spid-idp-button-logo" src="$spid_idp_timid_png" onerror="this.src='$spid_idp_timid_svg'; this.onerror=null;" alt="Tim ID" /></button>
                </li>
                <li class="spid-idp-support-link">
                    <a href="http://www.spid.gov.it">Maggiori info</a>
                </li>
                <li class="spid-idp-support-link">
                    <a href="http://www.spid.gov.it/#registrati">Non hai SPID?</a>
                </li>
            </ul>
        </div>
    </form>
BOTTONE;

    return $spid_bottone;
}
